---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-application.example.com
spec:
  selector:
    matchLabels:
      run: my-application.example.com
  replicas: 1
  template:
    metadata:
      labels:
        run: my-application.example.com
    spec:
      containers:
        - name: my-app
          image: cvi.jfrog.io/image-scan/my-application:MY_APP_VERSION
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: web
      imagePullSecrets:
        - name: regcred
