---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-application.example.com
spec:
  selector:
    matchLabels:
      run: my-application.example.com
  replicas: 1
  template:
    metadata:
      labels:
        run: my-application.example.com
    spec:
      containers:
        - name: my-app
          image: cvi.jfrog.io/image-scan/my-application:1.0-34
          imagePullPolicy: Always
          command:
            - "/my-application"
          ports:
            - containerPort: 8080
              name: web

---
apiVersion: v1
kind: Service
metadata:
  name: my-application-example-com
spec:
  selector:
    run: my-application.example.com
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
