---
apiVersion: v1
kind: Service
metadata:
  name: my-application-example-com
spec:
  selector:
    run: my-application.example.com
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
