version: 2.1

jobs:
  deploy_image:
    docker:
      - image: quay.io/crowdstrike/cloud-tools-image:latest
    steps:
      - checkout
      #- setup_remote_docker:
      #    version: "20.10.11"
      #    docker_layer_caching: true

      - run:
          name: CrowdStrike Image Policy check
          command: |
            # get API token
            FALCON_API_BEARER_TOKEN=$(curl \
            --silent \
            --header "Content-Type: application/x-www-form-urlencoded" \
            --data "client_id=${FALCON_CLIENT_ID}&client_secret=${FALCON_CLIENT_SECRET}" \
            --request POST \
            --url "https://api.crowdstrike.com/oauth2/token" | \
            python3 -c "import sys, json; print(json.load(sys.stdin)['access_token'])")

            IMAGE_VERSION=$(cat MY_APP_VERSION)
            RESPONSE=$(curl -s -X GET -H "Authorization: Bearer ${FALCON_API_BEARER_TOKEN}" \
                        "https://container-upload.us-1.crowdstrike.com/policy-checks?policy_type=image-prevention-policy&repository=cvi.jfrog.io/image-scan/my-application&tag=$IMAGE_VERSION" |\
                        jq -r '.resources[0]' )

            DENY=$(echo $RESPONSE | jq -r '.deny')
            ACTION=$(echo $RESPONSE | jq -r '.action')
            POLICY_NAME=$(echo $RESPONSE | jq -r '.policy.name')
            POLICY_DESCRIPTION=$(echo $RESPONSE | jq -r '.policy.description')

            if [[ "$DENY" == "true" && "$ACTION" == "block" ]]; then
                echo "============================================================"
                echo "IMAGE BLOCKED DUE TO SECURITY POLICY"
                echo "${POLICY_NAME} - ${POLICY_DESCRIPTION}"
                echo "============================================================"
                exit 1
            else
                echo "IMAGE OK TO BE DEPLOYED ACCORDING TO IMAGE ASSESSMENT POLICY"
                exit 0
            fi

      - run:
          name: Auth to google using service account
          command: |
            echo "Auth to google using service account"
            # echo -n $GOOGLE_SERVICE_KEY > key.json
            # gcloud auth activate-service-account $GOOGLE_SERVICE_ACCOUNT_NAME --key-file=key.json --project=$GOOGLE_PROJECT

      - run:
          name: Setup Kubernetes config
          command: |
            echo "Setup Kubernetes config"
            # Get auth from the gcloud service account 
            # gcloud container clusters get-credentials k8s-gke-helm-test-3 --zone us-central1-c --project $GOOGLE_PROJECT
            
            # Option 2 - inject a KUBE_CONFIG via a SECRET
            # mkdir -p $HOME/.kube
            # echo -n $KUBE_CONFIG_BASE64 | base64 -d >$HOME/.kube/config
            # kubectl config use-context gke_k8s-gke_us-central1-c_k8s-gke-helm-test-3

      - run:
          name: Deploy the manifest file
          command: |
            IMAGE_VERSION=$(cat MY_APP_VERSION)
            sed "s/MY_APP_VERSION/$IMAGE_VERSION/g" "my-application.yaml" > "generated-manifest.yml"
            cat generated-manifest.yaml
            # deploy the file on the k8s cluster
            # kubectl apply -f generated-manifest.yml

workflows:
  deploy_application:
    jobs:
      - deploy_image:
          context:
            - cicd
